
#include "HMI.h"

_HMI HMI = {

	.Heating = {
		.Command = 0,
		.Status = 0,
	},
	.Mode = {
		.Command = 0,
		.Status = 0,
	},
	.PowerReference = {
		.Decimals = 0,
		.Init = false,
		.Set.InputValue = 0,
		.Set.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 100,
	},
	.TemperatureReference = {
		.Decimals = 0,
		.Init = false,
		.Limit.Min = 0,
		.Limit.Max = 500,
		.Set.InputValue = 0,
		.Set.Value = 0,
	},
	.Profile = {
		.Times._0.Decimals = 0,
		.Times._0.Init = false,
		.Times._1.Decimals = 0,
		.Times._1.Init = false,
		.Times._2.Decimals = 0,
		.Times._2.Init = false,
		.Times._3.Decimals = 0,
		.Times._3.Init = false,
		.Times._4.Decimals = 0,
		.Times._4.Init = false,
		.Times._5.Decimals = 0,
		.Times._5.Init = false,
		.Values._0.Decimals = 0,
		.Values._0.Init = false,
		.Values._1.Decimals = 0,
		.Values._1.Init = false,
		.Values._2.Decimals = 0,
		.Values._2.Init = false,
		.Values._3.Decimals = 0,
		.Values._3.Init = false,
		.Values._4.Decimals = 0,
		.Values._4.Init = false,
		.Values._5.Decimals = 0,
		.Values._5.Init = false,
		.Times._0.Limit.Min = 0,
		.Times._0.Limit.Max = 0,
		.Times._1.Set.InputValue = 0,
		.Times._1.Set.Value = 0,
		.Times._0.Set.InputValue = 0,
		.Times._0.Set.Value = 0,
		.Times._1.Limit.Min = 0,
		.Times._1.Limit.Max = 0,
		.Times._2.Set.InputValue = 0,
		.Times._2.Set.Value = 0,
		.Times._2.Limit.Min = 0,
		.Times._2.Limit.Max = 0,
		.Times._3.Set.InputValue = 0,
		.Times._3.Set.Value = 0,
		.Times._3.Limit.Min = 0,
		.Times._3.Limit.Max = 0,
		.Times._4.Set.InputValue = 0,
		.Times._4.Set.Value = 0,
		.Times._4.Limit.Min = 0,
		.Times._4.Limit.Max = 0,
		.Times._5.Set.InputValue = 0,
		.Times._5.Set.Value = 0,
		.Times._5.Limit.Min = 0,
		.Times._5.Limit.Max = 0,
		.Values._0.Set.InputValue = 0,
		.Values._0.Set.Value = 0,
		.Values._0.Limit.Min = 0,
		.Values._0.Limit.Max = 500,
		.Values._1.Set.InputValue = 0,
		.Values._1.Set.Value = 0,
		.Values._1.Limit.Min = 0,
		.Values._1.Limit.Max = 500,
		.Values._2.Set.InputValue = 0,
		.Values._2.Set.Value = 0,
		.Values._2.Limit.Min = 0,
		.Values._2.Limit.Max = 500,
		.Values._3.Set.InputValue = 0,
		.Values._3.Set.Value = 0,
		.Values._3.Limit.Min = 0,
		.Values._3.Limit.Max = 500,
		.Values._4.Set.InputValue = 0,
		.Values._4.Set.Value = 0,
		.Values._4.Limit.Min = 0,
		.Values._4.Limit.Max = 500,
		.Values._5.Set.InputValue = 0,
		.Values._5.Set.Value = 0,
		.Values._5.Limit.Min = 0,
		.Values._5.Limit.Max = 500,
	},
	.PID = {
		.Error = 0,
		.Correction = 0,
		.PidOut = 0,
		.Reference = 0,
		.RawOut = 0,
		.Out = 0,
		.kpError = 0,
		.ProportionalCorrection = 0,
		.IntegralCorrection = 0,
		.DerivativeCorrection = 0,
		.AntiWindupContribute = 0,
		.kP.Decimals = 0,
		.kP.Init = false,
		.Ti.Decimals = 0,
		.Ti.Init = false,
		.Td.Decimals = 0,
		.Td.Init = false,
		.Gp.Decimals = 0,
		.Gp.Init = false,
		.PidMin.Decimals = 0,
		.PidMin.Init = false,
		.PidMax.Decimals = 0,
		.PidMax.Init = false,
		.OutMin.Decimals = 0,
		.OutMin.Init = false,
		.OutMax.Decimals = 0,
		.OutMax.Init = false,
		.OutGradient.Decimals = 0,
		.OutGradient.Init = false,
		.SetpointGradient.Decimals = 0,
		.SetpointGradient.Init = false,
		.Taw.Decimals = 0,
		.Taw.Init = false,
		.kP.Set.InputValue = 0,
		.kP.Set.Value = 0,
		.kP.Limit.Min = 0,
		.kP.Limit.Max = 500,
		.Ti.Set.InputValue = 0,
		.Ti.Set.Value = 0,
		.Ti.Limit.Min = 0.0001,
		.Ti.Limit.Max = 1000,
		.Td.Set.InputValue = 0,
		.Td.Set.Value = 0,
		.Td.Limit.Min = 0,
		.Td.Limit.Max = 100,
		.Gp.Set.InputValue = 0,
		.Gp.Set.Value = 0,
		.Gp.Limit.Min = 0,
		.Gp.Limit.Max = 500,
		.PidMin.Set.InputValue = 0,
		.PidMin.Set.Value = 0,
		.PidMin.Limit.Min = 0,
		.PidMin.Limit.Max = 0,
		.PidMax.Set.InputValue = 0,
		.PidMax.Set.Value = 0,
		.PidMax.Limit.Min = 0,
		.PidMax.Limit.Max = 0,
		.OutMin.Set.InputValue = 0,
		.OutMin.Set.Value = 0,
		.OutMin.Limit.Min = -100,
		.OutMin.Limit.Max = 100,
		.OutMax.Set.InputValue = 0,
		.OutMax.Set.Value = 0,
		.OutMax.Limit.Min = -100,
		.OutMax.Limit.Max = 100,
		.OutGradient.Set.InputValue = 0,
		.OutGradient.Set.Value = 0,
		.OutGradient.Limit.Min = 0.0001,
		.OutGradient.Limit.Max = 1000,
		.SetpointGradient.Set.InputValue = 0,
		.SetpointGradient.Set.Value = 0,
		.SetpointGradient.Limit.Min = 0.0001,
		.SetpointGradient.Limit.Max = 1000,
		.Taw.Set.InputValue = 0,
		.Taw.Set.Value = 0,
		.Taw.Limit.Min = 0.0001,
		.Taw.Limit.Max = 1000,
	},
	.ActualTemperature = {
		.Decimals = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 500,
	},
	.ActualPower = {
		.Decimals = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 100,
	},
};

_HMI PLC = {

	.Heating = {
		.Command = 0,
		.Status = 0,
	},
	.Mode = {
		.Command = 0,
		.Status = 0,
	},
	.PowerReference = {
		.Decimals = 0,
		.Init = false,
		.Set.InputValue = 0,
		.Set.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 100,
	},
	.TemperatureReference = {
		.Decimals = 0,
		.Init = false,
		.Limit.Min = 0,
		.Limit.Max = 500,
		.Set.InputValue = 0,
		.Set.Value = 0,
	},
	.Profile = {
		.Times._0.Decimals = 0,
		.Times._0.Init = false,
		.Times._1.Decimals = 0,
		.Times._1.Init = false,
		.Times._2.Decimals = 0,
		.Times._2.Init = false,
		.Times._3.Decimals = 0,
		.Times._3.Init = false,
		.Times._4.Decimals = 0,
		.Times._4.Init = false,
		.Times._5.Decimals = 0,
		.Times._5.Init = false,
		.Values._0.Decimals = 0,
		.Values._0.Init = false,
		.Values._1.Decimals = 0,
		.Values._1.Init = false,
		.Values._2.Decimals = 0,
		.Values._2.Init = false,
		.Values._3.Decimals = 0,
		.Values._3.Init = false,
		.Values._4.Decimals = 0,
		.Values._4.Init = false,
		.Values._5.Decimals = 0,
		.Values._5.Init = false,
		.Times._0.Limit.Min = 0,
		.Times._0.Limit.Max = 0,
		.Times._1.Set.InputValue = 0,
		.Times._1.Set.Value = 0,
		.Times._0.Set.InputValue = 0,
		.Times._0.Set.Value = 0,
		.Times._1.Limit.Min = 0,
		.Times._1.Limit.Max = 0,
		.Times._2.Set.InputValue = 0,
		.Times._2.Set.Value = 0,
		.Times._2.Limit.Min = 0,
		.Times._2.Limit.Max = 0,
		.Times._3.Set.InputValue = 0,
		.Times._3.Set.Value = 0,
		.Times._3.Limit.Min = 0,
		.Times._3.Limit.Max = 0,
		.Times._4.Set.InputValue = 0,
		.Times._4.Set.Value = 0,
		.Times._4.Limit.Min = 0,
		.Times._4.Limit.Max = 0,
		.Times._5.Set.InputValue = 0,
		.Times._5.Set.Value = 0,
		.Times._5.Limit.Min = 0,
		.Times._5.Limit.Max = 0,
		.Values._0.Set.InputValue = 0,
		.Values._0.Set.Value = 0,
		.Values._0.Limit.Min = 0,
		.Values._0.Limit.Max = 500,
		.Values._1.Set.InputValue = 0,
		.Values._1.Set.Value = 0,
		.Values._1.Limit.Min = 0,
		.Values._1.Limit.Max = 500,
		.Values._2.Set.InputValue = 0,
		.Values._2.Set.Value = 0,
		.Values._2.Limit.Min = 0,
		.Values._2.Limit.Max = 500,
		.Values._3.Set.InputValue = 0,
		.Values._3.Set.Value = 0,
		.Values._3.Limit.Min = 0,
		.Values._3.Limit.Max = 500,
		.Values._4.Set.InputValue = 0,
		.Values._4.Set.Value = 0,
		.Values._4.Limit.Min = 0,
		.Values._4.Limit.Max = 500,
		.Values._5.Set.InputValue = 0,
		.Values._5.Set.Value = 0,
		.Values._5.Limit.Min = 0,
		.Values._5.Limit.Max = 500,
	},
	.PID = {
		.Error = 0,
		.Correction = 0,
		.PidOut = 0,
		.Reference = 0,
		.RawOut = 0,
		.Out = 0,
		.kpError = 0,
		.ProportionalCorrection = 0,
		.IntegralCorrection = 0,
		.DerivativeCorrection = 0,
		.AntiWindupContribute = 0,
		.kP.Decimals = 0,
		.kP.Init = false,
		.Ti.Decimals = 0,
		.Ti.Init = false,
		.Td.Decimals = 0,
		.Td.Init = false,
		.Gp.Decimals = 0,
		.Gp.Init = false,
		.PidMin.Decimals = 0,
		.PidMin.Init = false,
		.PidMax.Decimals = 0,
		.PidMax.Init = false,
		.OutMin.Decimals = 0,
		.OutMin.Init = false,
		.OutMax.Decimals = 0,
		.OutMax.Init = false,
		.OutGradient.Decimals = 0,
		.OutGradient.Init = false,
		.SetpointGradient.Decimals = 0,
		.SetpointGradient.Init = false,
		.Taw.Decimals = 0,
		.Taw.Init = false,
		.kP.Set.InputValue = 0,
		.kP.Set.Value = 0,
		.kP.Limit.Min = 0,
		.kP.Limit.Max = 500,
		.Ti.Set.InputValue = 0,
		.Ti.Set.Value = 0,
		.Ti.Limit.Min = 0.0001,
		.Ti.Limit.Max = 1000,
		.Td.Set.InputValue = 0,
		.Td.Set.Value = 0,
		.Td.Limit.Min = 0,
		.Td.Limit.Max = 100,
		.Gp.Set.InputValue = 0,
		.Gp.Set.Value = 0,
		.Gp.Limit.Min = 0,
		.Gp.Limit.Max = 500,
		.PidMin.Set.InputValue = 0,
		.PidMin.Set.Value = 0,
		.PidMin.Limit.Min = 0,
		.PidMin.Limit.Max = 0,
		.PidMax.Set.InputValue = 0,
		.PidMax.Set.Value = 0,
		.PidMax.Limit.Min = 0,
		.PidMax.Limit.Max = 0,
		.OutMin.Set.InputValue = 0,
		.OutMin.Set.Value = 0,
		.OutMin.Limit.Min = -100,
		.OutMin.Limit.Max = 100,
		.OutMax.Set.InputValue = 0,
		.OutMax.Set.Value = 0,
		.OutMax.Limit.Min = -100,
		.OutMax.Limit.Max = 100,
		.OutGradient.Set.InputValue = 0,
		.OutGradient.Set.Value = 0,
		.OutGradient.Limit.Min = 0.0001,
		.OutGradient.Limit.Max = 1000,
		.SetpointGradient.Set.InputValue = 0,
		.SetpointGradient.Set.Value = 0,
		.SetpointGradient.Limit.Min = 0.0001,
		.SetpointGradient.Limit.Max = 1000,
		.Taw.Set.InputValue = 0,
		.Taw.Set.Value = 0,
		.Taw.Limit.Min = 0.0001,
		.Taw.Limit.Max = 1000,
	},
	.ActualTemperature = {
		.Decimals = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 500,
	},
	.ActualPower = {
		.Decimals = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 100,
	},
};

int id[175] = {
	4571,
	4572,
	4528,
	4529,
	4532,
	4533,
	4736,
	4737,
	4738,
	4739,
	4536,
	4537,
	4740,
	4741,
	4742,
	4743,
	5048,
	5049,
	5052,
	5053,
	5056,
	5057,
	5060,
	5061,
	5064,
	5065,
	5068,
	5069,
	5072,
	5073,
	5076,
	5077,
	5080,
	5081,
	5084,
	5085,
	5088,
	5089,
	5092,
	5093,
	5234,
	5235,
	5236,
	5237,
	5238,
	5239,
	5240,
	5241,
	5242,
	5243,
	5244,
	5245,
	5246,
	5247,
	5248,
	5249,
	5250,
	5251,
	5252,
	5253,
	5254,
	5255,
	5256,
	5257,
	5258,
	5259,
	5260,
	5261,
	5262,
	5263,
	5264,
	5265,
	5266,
	5267,
	5268,
	5269,
	5270,
	5271,
	5272,
	5273,
	5274,
	5275,
	5276,
	5277,
	5278,
	5279,
	5280,
	5281,
	4548,
	4549,
	4552,
	4553,
	4554,
	4557,
	4558,
	4559,
	4560,
	4561,
	4565,
	4752,
	4753,
	4756,
	4757,
	4760,
	4761,
	4766,
	4767,
	4770,
	4771,
	4774,
	4775,
	4778,
	4779,
	4782,
	4783,
	4786,
	4787,
	4790,
	4791,
	4794,
	4795,
	5002,
	5003,
	5004,
	5005,
	5006,
	5007,
	5008,
	5009,
	5010,
	5011,
	5012,
	5013,
	5014,
	5015,
	5016,
	5017,
	5018,
	5019,
	5020,
	5021,
	5022,
	5023,
	5024,
	5025,
	5026,
	5027,
	5028,
	5029,
	5030,
	5031,
	5032,
	5033,
	5034,
	5035,
	5036,
	5037,
	5038,
	5039,
	5040,
	5041,
	5042,
	5043,
	5044,
	5045,
	4568,
	4796,
	4797,
	4798,
	4799,
	4570,
	4800,
	4801,
	4848,
	4849
};

int type[175] = {
	INT,
	INT,
	INT,
	INT,
	INT,
	BOOL,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	BOOL,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	INT,
	BOOL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	REAL,
	REAL,
	REAL,
	REAL
};

void *HMI_pointer[175] = {
	(void*)&HMI.Heating.Command,
	(void*)&HMI.Heating.Status,
	(void*)&HMI.Mode.Command,
	(void*)&HMI.Mode.Status,
	(void*)&HMI.PowerReference.Decimals,
	(void*)&HMI.PowerReference.Init,
	(void*)&HMI.PowerReference.Set.InputValue,
	(void*)&HMI.PowerReference.Set.Value,
	(void*)&HMI.PowerReference.Limit.Min,
	(void*)&HMI.PowerReference.Limit.Max,
	(void*)&HMI.TemperatureReference.Decimals,
	(void*)&HMI.TemperatureReference.Init,
	(void*)&HMI.TemperatureReference.Limit.Min,
	(void*)&HMI.TemperatureReference.Limit.Max,
	(void*)&HMI.TemperatureReference.Set.InputValue,
	(void*)&HMI.TemperatureReference.Set.Value,
	(void*)&HMI.Profile.Times._0.Decimals,
	(void*)&HMI.Profile.Times._0.Init,
	(void*)&HMI.Profile.Times._1.Decimals,
	(void*)&HMI.Profile.Times._1.Init,
	(void*)&HMI.Profile.Times._2.Decimals,
	(void*)&HMI.Profile.Times._2.Init,
	(void*)&HMI.Profile.Times._3.Decimals,
	(void*)&HMI.Profile.Times._3.Init,
	(void*)&HMI.Profile.Times._4.Decimals,
	(void*)&HMI.Profile.Times._4.Init,
	(void*)&HMI.Profile.Times._5.Decimals,
	(void*)&HMI.Profile.Times._5.Init,
	(void*)&HMI.Profile.Values._0.Decimals,
	(void*)&HMI.Profile.Values._0.Init,
	(void*)&HMI.Profile.Values._1.Decimals,
	(void*)&HMI.Profile.Values._1.Init,
	(void*)&HMI.Profile.Values._2.Decimals,
	(void*)&HMI.Profile.Values._2.Init,
	(void*)&HMI.Profile.Values._3.Decimals,
	(void*)&HMI.Profile.Values._3.Init,
	(void*)&HMI.Profile.Values._4.Decimals,
	(void*)&HMI.Profile.Values._4.Init,
	(void*)&HMI.Profile.Values._5.Decimals,
	(void*)&HMI.Profile.Values._5.Init,
	(void*)&HMI.Profile.Times._0.Limit.Min,
	(void*)&HMI.Profile.Times._0.Limit.Max,
	(void*)&HMI.Profile.Times._1.Set.InputValue,
	(void*)&HMI.Profile.Times._1.Set.Value,
	(void*)&HMI.Profile.Times._0.Set.InputValue,
	(void*)&HMI.Profile.Times._0.Set.Value,
	(void*)&HMI.Profile.Times._1.Limit.Min,
	(void*)&HMI.Profile.Times._1.Limit.Max,
	(void*)&HMI.Profile.Times._2.Set.InputValue,
	(void*)&HMI.Profile.Times._2.Set.Value,
	(void*)&HMI.Profile.Times._2.Limit.Min,
	(void*)&HMI.Profile.Times._2.Limit.Max,
	(void*)&HMI.Profile.Times._3.Set.InputValue,
	(void*)&HMI.Profile.Times._3.Set.Value,
	(void*)&HMI.Profile.Times._3.Limit.Min,
	(void*)&HMI.Profile.Times._3.Limit.Max,
	(void*)&HMI.Profile.Times._4.Set.InputValue,
	(void*)&HMI.Profile.Times._4.Set.Value,
	(void*)&HMI.Profile.Times._4.Limit.Min,
	(void*)&HMI.Profile.Times._4.Limit.Max,
	(void*)&HMI.Profile.Times._5.Set.InputValue,
	(void*)&HMI.Profile.Times._5.Set.Value,
	(void*)&HMI.Profile.Times._5.Limit.Min,
	(void*)&HMI.Profile.Times._5.Limit.Max,
	(void*)&HMI.Profile.Values._0.Set.InputValue,
	(void*)&HMI.Profile.Values._0.Set.Value,
	(void*)&HMI.Profile.Values._0.Limit.Min,
	(void*)&HMI.Profile.Values._0.Limit.Max,
	(void*)&HMI.Profile.Values._1.Set.InputValue,
	(void*)&HMI.Profile.Values._1.Set.Value,
	(void*)&HMI.Profile.Values._1.Limit.Min,
	(void*)&HMI.Profile.Values._1.Limit.Max,
	(void*)&HMI.Profile.Values._2.Set.InputValue,
	(void*)&HMI.Profile.Values._2.Set.Value,
	(void*)&HMI.Profile.Values._2.Limit.Min,
	(void*)&HMI.Profile.Values._2.Limit.Max,
	(void*)&HMI.Profile.Values._3.Set.InputValue,
	(void*)&HMI.Profile.Values._3.Set.Value,
	(void*)&HMI.Profile.Values._3.Limit.Min,
	(void*)&HMI.Profile.Values._3.Limit.Max,
	(void*)&HMI.Profile.Values._4.Set.InputValue,
	(void*)&HMI.Profile.Values._4.Set.Value,
	(void*)&HMI.Profile.Values._4.Limit.Min,
	(void*)&HMI.Profile.Values._4.Limit.Max,
	(void*)&HMI.Profile.Values._5.Set.InputValue,
	(void*)&HMI.Profile.Values._5.Set.Value,
	(void*)&HMI.Profile.Values._5.Limit.Min,
	(void*)&HMI.Profile.Values._5.Limit.Max,
	(void*)&HMI.PID.Error,
	(void*)&HMI.PID.Correction,
	(void*)&HMI.PID.PidOut,
	(void*)&HMI.PID.Reference,
	(void*)&HMI.PID.RawOut,
	(void*)&HMI.PID.Out,
	(void*)&HMI.PID.kpError,
	(void*)&HMI.PID.ProportionalCorrection,
	(void*)&HMI.PID.IntegralCorrection,
	(void*)&HMI.PID.DerivativeCorrection,
	(void*)&HMI.PID.AntiWindupContribute,
	(void*)&HMI.PID.kP.Decimals,
	(void*)&HMI.PID.kP.Init,
	(void*)&HMI.PID.Ti.Decimals,
	(void*)&HMI.PID.Ti.Init,
	(void*)&HMI.PID.Td.Decimals,
	(void*)&HMI.PID.Td.Init,
	(void*)&HMI.PID.Gp.Decimals,
	(void*)&HMI.PID.Gp.Init,
	(void*)&HMI.PID.PidMin.Decimals,
	(void*)&HMI.PID.PidMin.Init,
	(void*)&HMI.PID.PidMax.Decimals,
	(void*)&HMI.PID.PidMax.Init,
	(void*)&HMI.PID.OutMin.Decimals,
	(void*)&HMI.PID.OutMin.Init,
	(void*)&HMI.PID.OutMax.Decimals,
	(void*)&HMI.PID.OutMax.Init,
	(void*)&HMI.PID.OutGradient.Decimals,
	(void*)&HMI.PID.OutGradient.Init,
	(void*)&HMI.PID.SetpointGradient.Decimals,
	(void*)&HMI.PID.SetpointGradient.Init,
	(void*)&HMI.PID.Taw.Decimals,
	(void*)&HMI.PID.Taw.Init,
	(void*)&HMI.PID.kP.Set.InputValue,
	(void*)&HMI.PID.kP.Set.Value,
	(void*)&HMI.PID.kP.Limit.Min,
	(void*)&HMI.PID.kP.Limit.Max,
	(void*)&HMI.PID.Ti.Set.InputValue,
	(void*)&HMI.PID.Ti.Set.Value,
	(void*)&HMI.PID.Ti.Limit.Min,
	(void*)&HMI.PID.Ti.Limit.Max,
	(void*)&HMI.PID.Td.Set.InputValue,
	(void*)&HMI.PID.Td.Set.Value,
	(void*)&HMI.PID.Td.Limit.Min,
	(void*)&HMI.PID.Td.Limit.Max,
	(void*)&HMI.PID.Gp.Set.InputValue,
	(void*)&HMI.PID.Gp.Set.Value,
	(void*)&HMI.PID.Gp.Limit.Min,
	(void*)&HMI.PID.Gp.Limit.Max,
	(void*)&HMI.PID.PidMin.Set.InputValue,
	(void*)&HMI.PID.PidMin.Set.Value,
	(void*)&HMI.PID.PidMin.Limit.Min,
	(void*)&HMI.PID.PidMin.Limit.Max,
	(void*)&HMI.PID.PidMax.Set.InputValue,
	(void*)&HMI.PID.PidMax.Set.Value,
	(void*)&HMI.PID.PidMax.Limit.Min,
	(void*)&HMI.PID.PidMax.Limit.Max,
	(void*)&HMI.PID.OutMin.Set.InputValue,
	(void*)&HMI.PID.OutMin.Set.Value,
	(void*)&HMI.PID.OutMin.Limit.Min,
	(void*)&HMI.PID.OutMin.Limit.Max,
	(void*)&HMI.PID.OutMax.Set.InputValue,
	(void*)&HMI.PID.OutMax.Set.Value,
	(void*)&HMI.PID.OutMax.Limit.Min,
	(void*)&HMI.PID.OutMax.Limit.Max,
	(void*)&HMI.PID.OutGradient.Set.InputValue,
	(void*)&HMI.PID.OutGradient.Set.Value,
	(void*)&HMI.PID.OutGradient.Limit.Min,
	(void*)&HMI.PID.OutGradient.Limit.Max,
	(void*)&HMI.PID.SetpointGradient.Set.InputValue,
	(void*)&HMI.PID.SetpointGradient.Set.Value,
	(void*)&HMI.PID.SetpointGradient.Limit.Min,
	(void*)&HMI.PID.SetpointGradient.Limit.Max,
	(void*)&HMI.PID.Taw.Set.InputValue,
	(void*)&HMI.PID.Taw.Set.Value,
	(void*)&HMI.PID.Taw.Limit.Min,
	(void*)&HMI.PID.Taw.Limit.Max,
	(void*)&HMI.ActualTemperature.Decimals,
	(void*)&HMI.ActualTemperature.Act.HMIValue,
	(void*)&HMI.ActualTemperature.Act.Value,
	(void*)&HMI.ActualTemperature.Limit.Min,
	(void*)&HMI.ActualTemperature.Limit.Max,
	(void*)&HMI.ActualPower.Decimals,
	(void*)&HMI.ActualPower.Act.HMIValue,
	(void*)&HMI.ActualPower.Act.Value,
	(void*)&HMI.ActualPower.Limit.Min,
	(void*)&HMI.ActualPower.Limit.Max
};

void *PLC_pointer[175] = {
	(void*)&PLC.Heating.Command,
	(void*)&PLC.Heating.Status,
	(void*)&PLC.Mode.Command,
	(void*)&PLC.Mode.Status,
	(void*)&PLC.PowerReference.Decimals,
	(void*)&PLC.PowerReference.Init,
	(void*)&PLC.PowerReference.Set.InputValue,
	(void*)&PLC.PowerReference.Set.Value,
	(void*)&PLC.PowerReference.Limit.Min,
	(void*)&PLC.PowerReference.Limit.Max,
	(void*)&PLC.TemperatureReference.Decimals,
	(void*)&PLC.TemperatureReference.Init,
	(void*)&PLC.TemperatureReference.Limit.Min,
	(void*)&PLC.TemperatureReference.Limit.Max,
	(void*)&PLC.TemperatureReference.Set.InputValue,
	(void*)&PLC.TemperatureReference.Set.Value,
	(void*)&PLC.Profile.Times._0.Decimals,
	(void*)&PLC.Profile.Times._0.Init,
	(void*)&PLC.Profile.Times._1.Decimals,
	(void*)&PLC.Profile.Times._1.Init,
	(void*)&PLC.Profile.Times._2.Decimals,
	(void*)&PLC.Profile.Times._2.Init,
	(void*)&PLC.Profile.Times._3.Decimals,
	(void*)&PLC.Profile.Times._3.Init,
	(void*)&PLC.Profile.Times._4.Decimals,
	(void*)&PLC.Profile.Times._4.Init,
	(void*)&PLC.Profile.Times._5.Decimals,
	(void*)&PLC.Profile.Times._5.Init,
	(void*)&PLC.Profile.Values._0.Decimals,
	(void*)&PLC.Profile.Values._0.Init,
	(void*)&PLC.Profile.Values._1.Decimals,
	(void*)&PLC.Profile.Values._1.Init,
	(void*)&PLC.Profile.Values._2.Decimals,
	(void*)&PLC.Profile.Values._2.Init,
	(void*)&PLC.Profile.Values._3.Decimals,
	(void*)&PLC.Profile.Values._3.Init,
	(void*)&PLC.Profile.Values._4.Decimals,
	(void*)&PLC.Profile.Values._4.Init,
	(void*)&PLC.Profile.Values._5.Decimals,
	(void*)&PLC.Profile.Values._5.Init,
	(void*)&PLC.Profile.Times._0.Limit.Min,
	(void*)&PLC.Profile.Times._0.Limit.Max,
	(void*)&PLC.Profile.Times._1.Set.InputValue,
	(void*)&PLC.Profile.Times._1.Set.Value,
	(void*)&PLC.Profile.Times._0.Set.InputValue,
	(void*)&PLC.Profile.Times._0.Set.Value,
	(void*)&PLC.Profile.Times._1.Limit.Min,
	(void*)&PLC.Profile.Times._1.Limit.Max,
	(void*)&PLC.Profile.Times._2.Set.InputValue,
	(void*)&PLC.Profile.Times._2.Set.Value,
	(void*)&PLC.Profile.Times._2.Limit.Min,
	(void*)&PLC.Profile.Times._2.Limit.Max,
	(void*)&PLC.Profile.Times._3.Set.InputValue,
	(void*)&PLC.Profile.Times._3.Set.Value,
	(void*)&PLC.Profile.Times._3.Limit.Min,
	(void*)&PLC.Profile.Times._3.Limit.Max,
	(void*)&PLC.Profile.Times._4.Set.InputValue,
	(void*)&PLC.Profile.Times._4.Set.Value,
	(void*)&PLC.Profile.Times._4.Limit.Min,
	(void*)&PLC.Profile.Times._4.Limit.Max,
	(void*)&PLC.Profile.Times._5.Set.InputValue,
	(void*)&PLC.Profile.Times._5.Set.Value,
	(void*)&PLC.Profile.Times._5.Limit.Min,
	(void*)&PLC.Profile.Times._5.Limit.Max,
	(void*)&PLC.Profile.Values._0.Set.InputValue,
	(void*)&PLC.Profile.Values._0.Set.Value,
	(void*)&PLC.Profile.Values._0.Limit.Min,
	(void*)&PLC.Profile.Values._0.Limit.Max,
	(void*)&PLC.Profile.Values._1.Set.InputValue,
	(void*)&PLC.Profile.Values._1.Set.Value,
	(void*)&PLC.Profile.Values._1.Limit.Min,
	(void*)&PLC.Profile.Values._1.Limit.Max,
	(void*)&PLC.Profile.Values._2.Set.InputValue,
	(void*)&PLC.Profile.Values._2.Set.Value,
	(void*)&PLC.Profile.Values._2.Limit.Min,
	(void*)&PLC.Profile.Values._2.Limit.Max,
	(void*)&PLC.Profile.Values._3.Set.InputValue,
	(void*)&PLC.Profile.Values._3.Set.Value,
	(void*)&PLC.Profile.Values._3.Limit.Min,
	(void*)&PLC.Profile.Values._3.Limit.Max,
	(void*)&PLC.Profile.Values._4.Set.InputValue,
	(void*)&PLC.Profile.Values._4.Set.Value,
	(void*)&PLC.Profile.Values._4.Limit.Min,
	(void*)&PLC.Profile.Values._4.Limit.Max,
	(void*)&PLC.Profile.Values._5.Set.InputValue,
	(void*)&PLC.Profile.Values._5.Set.Value,
	(void*)&PLC.Profile.Values._5.Limit.Min,
	(void*)&PLC.Profile.Values._5.Limit.Max,
	(void*)&PLC.PID.Error,
	(void*)&PLC.PID.Correction,
	(void*)&PLC.PID.PidOut,
	(void*)&PLC.PID.Reference,
	(void*)&PLC.PID.RawOut,
	(void*)&PLC.PID.Out,
	(void*)&PLC.PID.kpError,
	(void*)&PLC.PID.ProportionalCorrection,
	(void*)&PLC.PID.IntegralCorrection,
	(void*)&PLC.PID.DerivativeCorrection,
	(void*)&PLC.PID.AntiWindupContribute,
	(void*)&PLC.PID.kP.Decimals,
	(void*)&PLC.PID.kP.Init,
	(void*)&PLC.PID.Ti.Decimals,
	(void*)&PLC.PID.Ti.Init,
	(void*)&PLC.PID.Td.Decimals,
	(void*)&PLC.PID.Td.Init,
	(void*)&PLC.PID.Gp.Decimals,
	(void*)&PLC.PID.Gp.Init,
	(void*)&PLC.PID.PidMin.Decimals,
	(void*)&PLC.PID.PidMin.Init,
	(void*)&PLC.PID.PidMax.Decimals,
	(void*)&PLC.PID.PidMax.Init,
	(void*)&PLC.PID.OutMin.Decimals,
	(void*)&PLC.PID.OutMin.Init,
	(void*)&PLC.PID.OutMax.Decimals,
	(void*)&PLC.PID.OutMax.Init,
	(void*)&PLC.PID.OutGradient.Decimals,
	(void*)&PLC.PID.OutGradient.Init,
	(void*)&PLC.PID.SetpointGradient.Decimals,
	(void*)&PLC.PID.SetpointGradient.Init,
	(void*)&PLC.PID.Taw.Decimals,
	(void*)&PLC.PID.Taw.Init,
	(void*)&PLC.PID.kP.Set.InputValue,
	(void*)&PLC.PID.kP.Set.Value,
	(void*)&PLC.PID.kP.Limit.Min,
	(void*)&PLC.PID.kP.Limit.Max,
	(void*)&PLC.PID.Ti.Set.InputValue,
	(void*)&PLC.PID.Ti.Set.Value,
	(void*)&PLC.PID.Ti.Limit.Min,
	(void*)&PLC.PID.Ti.Limit.Max,
	(void*)&PLC.PID.Td.Set.InputValue,
	(void*)&PLC.PID.Td.Set.Value,
	(void*)&PLC.PID.Td.Limit.Min,
	(void*)&PLC.PID.Td.Limit.Max,
	(void*)&PLC.PID.Gp.Set.InputValue,
	(void*)&PLC.PID.Gp.Set.Value,
	(void*)&PLC.PID.Gp.Limit.Min,
	(void*)&PLC.PID.Gp.Limit.Max,
	(void*)&PLC.PID.PidMin.Set.InputValue,
	(void*)&PLC.PID.PidMin.Set.Value,
	(void*)&PLC.PID.PidMin.Limit.Min,
	(void*)&PLC.PID.PidMin.Limit.Max,
	(void*)&PLC.PID.PidMax.Set.InputValue,
	(void*)&PLC.PID.PidMax.Set.Value,
	(void*)&PLC.PID.PidMax.Limit.Min,
	(void*)&PLC.PID.PidMax.Limit.Max,
	(void*)&PLC.PID.OutMin.Set.InputValue,
	(void*)&PLC.PID.OutMin.Set.Value,
	(void*)&PLC.PID.OutMin.Limit.Min,
	(void*)&PLC.PID.OutMin.Limit.Max,
	(void*)&PLC.PID.OutMax.Set.InputValue,
	(void*)&PLC.PID.OutMax.Set.Value,
	(void*)&PLC.PID.OutMax.Limit.Min,
	(void*)&PLC.PID.OutMax.Limit.Max,
	(void*)&PLC.PID.OutGradient.Set.InputValue,
	(void*)&PLC.PID.OutGradient.Set.Value,
	(void*)&PLC.PID.OutGradient.Limit.Min,
	(void*)&PLC.PID.OutGradient.Limit.Max,
	(void*)&PLC.PID.SetpointGradient.Set.InputValue,
	(void*)&PLC.PID.SetpointGradient.Set.Value,
	(void*)&PLC.PID.SetpointGradient.Limit.Min,
	(void*)&PLC.PID.SetpointGradient.Limit.Max,
	(void*)&PLC.PID.Taw.Set.InputValue,
	(void*)&PLC.PID.Taw.Set.Value,
	(void*)&PLC.PID.Taw.Limit.Min,
	(void*)&PLC.PID.Taw.Limit.Max,
	(void*)&PLC.ActualTemperature.Decimals,
	(void*)&PLC.ActualTemperature.Act.HMIValue,
	(void*)&PLC.ActualTemperature.Act.Value,
	(void*)&PLC.ActualTemperature.Limit.Min,
	(void*)&PLC.ActualTemperature.Limit.Max,
	(void*)&PLC.ActualPower.Decimals,
	(void*)&PLC.ActualPower.Act.HMIValue,
	(void*)&PLC.ActualPower.Act.Value,
	(void*)&PLC.ActualPower.Limit.Min,
	(void*)&PLC.ActualPower.Limit.Max
};
  