
#include "HMI.h"

_HMI HMI = {

	.BatteryLevel = {
		.Decimals = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 100,
	},
	.Light = {
		.Command = 0,
		.Status = 0,
	},
	.Temperature = {
		.Decimals = 0,
		.Init = false,
		.Set.InputValue = 0,
		.Set.Value = 0,
		.Limit.Min = 20,
		.Limit.Max = 70,
	},
	.Pressure = {
		.Decimals = 1,
		.Init = false,
		.Set.InputValue = 0,
		.Set.Value = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 10,
	},
	.LightOn = {
		.Status = 0,
		.Reaction = 0,
		.Ts = 0,
		.Q = false,
	},
};

_HMI PLC = {

	.BatteryLevel = {
		.Decimals = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 100,
	},
	.Light = {
		.Command = 0,
		.Status = 0,
	},
	.Temperature = {
		.Decimals = 0,
		.Init = false,
		.Set.InputValue = 0,
		.Set.Value = 0,
		.Limit.Min = 20,
		.Limit.Max = 70,
	},
	.Pressure = {
		.Decimals = 1,
		.Init = false,
		.Set.InputValue = 0,
		.Set.Value = 0,
		.Act.HMIValue = 0,
		.Act.Value = 0,
		.Limit.Min = 0,
		.Limit.Max = 10,
	},
	.LightOn = {
		.Status = 0,
		.Reaction = 0,
		.Ts = 0,
		.Q = false,
	},
};

int id[25] = {
	87,
	98,
	99,
	100,
	101,
	88,
	89,
	108,
	109,
	127,
	128,
	129,
	130,
	93,
	94,
	118,
	119,
	121,
	122,
	123,
	124,
	102,
	103,
	104,
	105
};

int type[25] = {
	INT,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	INT,
	INT,
	BOOL,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	BOOL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	REAL,
	INT,
	INT,
	TIMESTAMP,
	BOOL
};

void *HMI_pointer[25] = {
	(void*)&HMI.BatteryLevel.Decimals,
	(void*)&HMI.BatteryLevel.Act.HMIValue,
	(void*)&HMI.BatteryLevel.Act.Value,
	(void*)&HMI.BatteryLevel.Limit.Min,
	(void*)&HMI.BatteryLevel.Limit.Max,
	(void*)&HMI.Light.Command,
	(void*)&HMI.Light.Status,
	(void*)&HMI.Temperature.Decimals,
	(void*)&HMI.Temperature.Init,
	(void*)&HMI.Temperature.Set.InputValue,
	(void*)&HMI.Temperature.Set.Value,
	(void*)&HMI.Temperature.Limit.Min,
	(void*)&HMI.Temperature.Limit.Max,
	(void*)&HMI.Pressure.Decimals,
	(void*)&HMI.Pressure.Init,
	(void*)&HMI.Pressure.Set.InputValue,
	(void*)&HMI.Pressure.Set.Value,
	(void*)&HMI.Pressure.Act.HMIValue,
	(void*)&HMI.Pressure.Act.Value,
	(void*)&HMI.Pressure.Limit.Min,
	(void*)&HMI.Pressure.Limit.Max,
	(void*)&HMI.LightOn.Status,
	(void*)&HMI.LightOn.Reaction,
	(void*)&HMI.LightOn.Ts,
	(void*)&HMI.LightOn.Q
};

void *PLC_pointer[25] = {
	(void*)&PLC.BatteryLevel.Decimals,
	(void*)&PLC.BatteryLevel.Act.HMIValue,
	(void*)&PLC.BatteryLevel.Act.Value,
	(void*)&PLC.BatteryLevel.Limit.Min,
	(void*)&PLC.BatteryLevel.Limit.Max,
	(void*)&PLC.Light.Command,
	(void*)&PLC.Light.Status,
	(void*)&PLC.Temperature.Decimals,
	(void*)&PLC.Temperature.Init,
	(void*)&PLC.Temperature.Set.InputValue,
	(void*)&PLC.Temperature.Set.Value,
	(void*)&PLC.Temperature.Limit.Min,
	(void*)&PLC.Temperature.Limit.Max,
	(void*)&PLC.Pressure.Decimals,
	(void*)&PLC.Pressure.Init,
	(void*)&PLC.Pressure.Set.InputValue,
	(void*)&PLC.Pressure.Set.Value,
	(void*)&PLC.Pressure.Act.HMIValue,
	(void*)&PLC.Pressure.Act.Value,
	(void*)&PLC.Pressure.Limit.Min,
	(void*)&PLC.Pressure.Limit.Max,
	(void*)&PLC.LightOn.Status,
	(void*)&PLC.LightOn.Reaction,
	(void*)&PLC.LightOn.Ts,
	(void*)&PLC.LightOn.Q
};
  